SELECT C.COURSE_NAME, E.GRADE, S.S_ID
FROM COURSE AS C, ENROLLMENT AS E, STUDENT AS S, COURSE_SECTION AS CS
    WHERE E.C_SEC_ID = CS.C_SEC_ID 
        AND CS.COURSE_ID = C.COURSE_ID 
        AND E.S_ID = S.S_ID 
        AND S.S_LAST = 'Jones' 
        AND S.S_FIRST = 'Tammy';
