LOAD DATA LOCAL INFILE '/Users/gdiaz/gil-workspace/db-modeling-design-final-project/course_section.csv' 
INTO TABLE COURSE_SECTION
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 2 ROWS
(C_SEC_ID,COURSE_ID,TERM_ID,SEC_NUM,F_ID,MTG_DAYS,@START_TIME,@END_TIME,LOC_ID,MAX_ENRL)
SET START_TIME = TIME_FORMAT(
		CAST(
			CONCAT(CASE WHEN RIGHT(@START_TIME,2) = 'PM' 
				THEN
					HOUR(@START_TIME) + 12 
				ELSE 
					HOUR(@START_TIME) END, ':',
					MINUTE(@START_TIME)) AS CHAR CHARACTER SET utf8), '%T'),
	END_TIME = TIME_FORMAT(
		CAST(
			CONCAT(CASE WHEN RIGHT(@END_TIME,2) = 'PM'
				THEN
					HOUR(@END_TIME) + 12 
				ELSE HOUR(@END_TIME) END, ':',
					MINUTE(@END_TIME)) AS CHAR CHARACTER SET utf8), '%T');
                    

SELECT * FROM COURSE_SECTION;
