LOAD DATA LOCAL INFILE '/Users/gdiaz/gil-workspace/db-modeling-design-final-project/term.csv' 
INTO TABLE TERM
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 2 LINES
(TERM_ID,TERM_DESC,STATUS,@START_DATE)
SET START_DATE = STR_TO_DATE(@START_DATE, '%d-%b-%y');

SELECT * FROM TERM;
