DROP TABLE IF EXISTS ENROLLMENT_NUMBERS;
CREATE TABLE ENROLLMENT_NUMBERS(
	ENR_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    COURSE_NO VARCHAR(15) NOT NULL,
    C_SEC_ID INTEGER NOT NULL,
    S_ENRL INTEGER NOT NULL
    CHECK (S_ENRL > 0)
);
INSERT INTO ENROLLMENT_NUMBERS (COURSE_NO, C_SEC_ID, S_ENRL)
SELECT A.COURSE_NO, B.C_SEC_ID, COUNT(C.C_SEC_ID) AS S_ENRL 
FROM COURSE AS A, COURSE_SECTION AS B, ENROLLMENT AS C
WHERE A.COURSE_ID = B.COURSE_ID AND B.C_SEC_ID = C.C_SEC_ID AND B.TERM_ID = 5
GROUP BY C_SEC_ID
ORDER BY S_ENRL;
