SELECT S_FIRST, S_LAST FROM STUDENT WHERE S_CLASS = 
    (
        SELECT S_CLASS FROM STUDENT WHERE S_FIRST LIKE 'Jorge' AND S_LAST LIKE 'Perez'
    )
    AND S_ID IN 
    (
        SELECT S_ID FROM ENROLLMENT WHERE C_SEC_ID IN
        (
            SELECT C_SEC_ID FROM ENROLLMENT WHERE S_ID = 2
        )
    );
